IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'amc')
BEGIN
    EXEC('CREATE SCHEMA amc');
END
GO

IF OBJECT_ID(N'[amc].[WORKFLOW_STEP_RUNS]', N'U') IS NOT NULL
    DROP TABLE [amc].[WORKFLOW_STEP_RUNS];
GO

IF OBJECT_ID(N'[amc].[WORKFLOW_RUNS]', N'U') IS NOT NULL
    DROP TABLE [amc].[WORKFLOW_RUNS];
GO

IF OBJECT_ID(N'[amc].[AGENT_WORKFLOW_STEPS]', N'U') IS NOT NULL
    DROP TABLE [amc].[AGENT_WORKFLOW_STEPS];
GO

IF OBJECT_ID(N'[amc].[AGENT_WORKFLOWS]', N'U') IS NOT NULL
    DROP TABLE [amc].[AGENT_WORKFLOWS];
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'WORKFLOW_RUN_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [WORKFLOW_RUN_ID] NVARCHAR(64) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'WORKFLOW_STEP_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [WORKFLOW_STEP_ID] NVARCHAR(64) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'WORKFLOW_STEP_RUN_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [WORKFLOW_STEP_RUN_ID] NVARCHAR(64) NULL;
GO

CREATE TABLE [amc].[AGENT_WORKFLOWS] (
    [ID] NVARCHAR(64) NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX) NOT NULL,
    [IS_ACTIVE] BIT NOT NULL,
    [VERSION] NVARCHAR(50) NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL,
    CONSTRAINT [PK_AGENT_WORKFLOWS] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [amc].[AGENT_WORKFLOW_STEPS] (
    [ID] NVARCHAR(64) NOT NULL,
    [WORKFLOW_ID] NVARCHAR(64) NOT NULL,
    [STEP_ORDER] INT NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [STEP_TYPE] INT NOT NULL,
    [AGENT_ID] NVARCHAR(64) NULL,
    [SWARM_ID] NVARCHAR(64) NULL,
    [STATIC_INPUT] NVARCHAR(MAX) NULL,
    [INPUT_SOURCE] INT NOT NULL,
    [PROMPT_OVERRIDE] NVARCHAR(MAX) NULL,
    [REQUIRE_APPROVAL] BIT NOT NULL,
    [TIMEOUT_SECONDS] INT NOT NULL,
    [CONTINUE_ON_FAILURE] BIT NOT NULL,
    CONSTRAINT [PK_AGENT_WORKFLOW_STEPS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_AGENT_WORKFLOW_STEPS_WORKFLOW] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [amc].[AGENT_WORKFLOWS]([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_AGENT_WORKFLOW_STEPS_AGENT] FOREIGN KEY ([AGENT_ID]) REFERENCES [amc].[AGENTS]([ID]),
    CONSTRAINT [FK_AGENT_WORKFLOW_STEPS_SWARM] FOREIGN KEY ([SWARM_ID]) REFERENCES [amc].[SWARMS]([ID])
);
GO

CREATE TABLE [amc].[WORKFLOW_RUNS] (
    [ID] NVARCHAR(64) NOT NULL,
    [WORKFLOW_ID] NVARCHAR(64) NOT NULL,
    [WORKFLOW_NAME_SNAPSHOT] NVARCHAR(255) NOT NULL,
    [STATUS] INT NOT NULL,
    [INPUT] NVARCHAR(MAX) NULL,
    [OUTPUT] NVARCHAR(MAX) NULL,
    [ERROR_MESSAGE] NVARCHAR(MAX) NULL,
    [CREATED_AT] DATETIME2 NOT NULL,
    [STARTED_AT] DATETIME2 NULL,
    [COMPLETED_AT] DATETIME2 NULL,
    [CURRENT_STEP_ORDER] INT NOT NULL,
    CONSTRAINT [PK_WORKFLOW_RUNS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_WORKFLOW_RUNS_WORKFLOW] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [amc].[AGENT_WORKFLOWS]([ID]) ON DELETE CASCADE
);
GO

CREATE TABLE [amc].[WORKFLOW_STEP_RUNS] (
    [ID] NVARCHAR(64) NOT NULL,
    [WORKFLOW_RUN_ID] NVARCHAR(64) NOT NULL,
    [WORKFLOW_STEP_ID] NVARCHAR(64) NOT NULL,
    [STEP_NAME_SNAPSHOT] NVARCHAR(255) NOT NULL,
    [STEP_ORDER] INT NOT NULL,
    [STATUS] INT NOT NULL,
    [INPUT] NVARCHAR(MAX) NULL,
    [OUTPUT] NVARCHAR(MAX) NULL,
    [ERROR_MESSAGE] NVARCHAR(MAX) NULL,
    [AGENT_TASK_ID] NVARCHAR(64) NULL,
    [CREATED_AT] DATETIME2 NOT NULL,
    [STARTED_AT] DATETIME2 NULL,
    [COMPLETED_AT] DATETIME2 NULL,
    CONSTRAINT [PK_WORKFLOW_STEP_RUNS] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_WORKFLOW_STEP_RUNS_RUN] FOREIGN KEY ([WORKFLOW_RUN_ID]) REFERENCES [amc].[WORKFLOW_RUNS]([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_WORKFLOW_STEP_RUNS_STEP] FOREIGN KEY ([WORKFLOW_STEP_ID]) REFERENCES [amc].[AGENT_WORKFLOW_STEPS]([ID]),
    CONSTRAINT [FK_WORKFLOW_STEP_RUNS_TASK] FOREIGN KEY ([AGENT_TASK_ID]) REFERENCES [amc].[AGENT_TASKS]([ID])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_WORKFLOW_STEPS_WORKFLOW_ID_STEP_ORDER' AND object_id = OBJECT_ID(N'[amc].[AGENT_WORKFLOW_STEPS]'))
    CREATE UNIQUE INDEX [IX_AGENT_WORKFLOW_STEPS_WORKFLOW_ID_STEP_ORDER]
        ON [amc].[AGENT_WORKFLOW_STEPS] ([WORKFLOW_ID], [STEP_ORDER]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_WORKFLOW_RUNS_WORKFLOW_ID_CREATED_AT' AND object_id = OBJECT_ID(N'[amc].[WORKFLOW_RUNS]'))
    CREATE INDEX [IX_WORKFLOW_RUNS_WORKFLOW_ID_CREATED_AT]
        ON [amc].[WORKFLOW_RUNS] ([WORKFLOW_ID], [CREATED_AT] DESC);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_WORKFLOW_STEP_RUNS_WORKFLOW_RUN_ID_STEP_ORDER' AND object_id = OBJECT_ID(N'[amc].[WORKFLOW_STEP_RUNS]'))
    CREATE INDEX [IX_WORKFLOW_STEP_RUNS_WORKFLOW_RUN_ID_STEP_ORDER]
        ON [amc].[WORKFLOW_STEP_RUNS] ([WORKFLOW_RUN_ID], [STEP_ORDER]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_TASKS_WORKFLOW_RUN_ID' AND object_id = OBJECT_ID(N'[amc].[AGENT_TASKS]'))
    CREATE INDEX [IX_AGENT_TASKS_WORKFLOW_RUN_ID]
        ON [amc].[AGENT_TASKS] ([WORKFLOW_RUN_ID]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_TASKS_WORKFLOW_STEP_ID' AND object_id = OBJECT_ID(N'[amc].[AGENT_TASKS]'))
    CREATE INDEX [IX_AGENT_TASKS_WORKFLOW_STEP_ID]
        ON [amc].[AGENT_TASKS] ([WORKFLOW_STEP_ID]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_TASKS_WORKFLOW_STEP_RUN_ID' AND object_id = OBJECT_ID(N'[amc].[AGENT_TASKS]'))
    CREATE INDEX [IX_AGENT_TASKS_WORKFLOW_STEP_RUN_ID]
        ON [amc].[AGENT_TASKS] ([WORKFLOW_STEP_RUN_ID]);
GO
