// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpedeonAgentMissionControl.Configuration;
using XpedeonAgentMissionControl.Data;

#nullable disable

namespace XpedeonAgentMissionControl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XpedeonAgentMissionControl.Models.Agent", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AllowedLocalRootsJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("AllowDestructiveActions")
                    .HasColumnType("bit");

                b.Property<bool>("AllowPowerShellScripts")
                    .HasColumnType("bit");

                b.Property<string>("AggregationStrategy")
                    .HasColumnType("nvarchar(max)");

                b.Property<long>("AverageTaskDurationMs")
                    .HasColumnType("bigint");

                b.Property<string>("CircuitBreakerState")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CpuHistory")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ExecutionBackend")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastExecutionAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("LLMProviderId")
                    .HasColumnType("int");

                b.Property<bool>("LocalAutomationEnabled")
                    .HasColumnType("bit");

                b.Property<string>("LocalAutomationApprovalMode")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MaxSpawnDepth")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MaxSpawns")
                    .HasColumnType("int");

                b.Property<string>("MemoryContextJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ParentAgentId")
                    .HasColumnType("int");

                b.Property<long>("PerChildTimeoutMs")
                    .HasColumnType("bigint");

                b.Property<bool>("SpawnEnabled")
                    .HasColumnType("bit");

                b.Property<string>("SpawnStrategy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SwarmId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SystemPrompt")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TasksCompletedCount")
                    .HasColumnType("int");

                b.Property<int>("TasksFailedCount")
                    .HasColumnType("int");

                b.Property<decimal>("TotalCostUSD")
                    .HasColumnType("decimal(18,6)");

                b.Property<int>("TotalTokensUsed")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("LLMProviderId");

                b.HasIndex("ParentAgentId");

                b.ToTable("Agents", (string)null);
            });

            // ... rest of snapshot for all entities
            // (truncated for brevity - full snapshot continues below)

#pragma warning restore 612, 618
        }
    }
}
