SET NOCOUNT ON;
GO

IF SCHEMA_ID(N'amc') IS NULL
BEGIN
    THROW 50000, 'Schema [amc] does not exist in this database.', 1;
END
GO

IF COL_LENGTH(N'amc.AGENTS', N'LOCAL_AUTOMATION_APPROVAL_MODE') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENTS]
    ADD [LOCAL_AUTOMATION_APPROVAL_MODE] int NOT NULL
        CONSTRAINT [DF_AMC_AGENTS_LOCAL_AUTOMATION_APPROVAL_MODE] DEFAULT ((1));
END
GO
