USE [BZMGTLDB];
GO

IF COL_LENGTH('amc.AGENTS', 'EXECUTION_BACKEND') IS NULL
    ALTER TABLE [amc].[AGENTS] ADD [EXECUTION_BACKEND] INT NOT NULL CONSTRAINT [DF_AGENTS_EXECUTION_BACKEND] DEFAULT (0);
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'EXECUTION_BACKEND_SNAPSHOT') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXECUTION_BACKEND_SNAPSHOT] INT NOT NULL CONSTRAINT [DF_AGENT_TASKS_EXECUTION_BACKEND_SNAPSHOT] DEFAULT (0);
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_RUN_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_RUN_ID] NVARCHAR(255) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_BACKEND') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_BACKEND] NVARCHAR(100) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_STATUS') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_STATUS] INT NOT NULL CONSTRAINT [DF_AGENT_TASKS_EXTERNAL_STATUS] DEFAULT (0);
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_SUBMITTED_AT') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_SUBMITTED_AT] DATETIME2 NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_LAST_SYNCED_AT') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_LAST_SYNCED_AT] DATETIME2 NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_TRACE') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_TRACE] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_RESULT_JSON') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_RESULT_JSON] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'EXTERNAL_ERROR') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [EXTERNAL_ERROR] NVARCHAR(MAX) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_TASKS_EXTERNAL_RUN_ID' AND object_id = OBJECT_ID(N'[amc].[AGENT_TASKS]'))
    CREATE INDEX [IX_AGENT_TASKS_EXTERNAL_RUN_ID] ON [amc].[AGENT_TASKS] ([EXTERNAL_RUN_ID]);
GO
