SET NOCOUNT ON;
GO

IF SCHEMA_ID(N'amc') IS NULL
BEGIN
    THROW 50000, 'Schema [amc] does not exist in this database.', 1;
END
GO

IF COL_LENGTH(N'amc.AGENTS', N'LOCAL_AUTOMATION_ENABLED') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENTS]
    ADD [LOCAL_AUTOMATION_ENABLED] bit NOT NULL
        CONSTRAINT [DF_AMC_AGENTS_LOCAL_AUTOMATION_ENABLED] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.AGENTS', N'ALLOW_POWER_SHELL_SCRIPTS') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENTS]
    ADD [ALLOW_POWER_SHELL_SCRIPTS] bit NOT NULL
        CONSTRAINT [DF_AMC_AGENTS_ALLOW_POWER_SHELL_SCRIPTS] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.AGENTS', N'ALLOW_DESTRUCTIVE_ACTIONS') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENTS]
    ADD [ALLOW_DESTRUCTIVE_ACTIONS] bit NOT NULL
        CONSTRAINT [DF_AMC_AGENTS_ALLOW_DESTRUCTIVE_ACTIONS] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.AGENTS', N'ALLOWED_LOCAL_ROOTS_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENTS]
    ADD [ALLOWED_LOCAL_ROOTS_JSON] nvarchar(max) NULL;
END
GO

IF COL_LENGTH(N'amc.AGENT_TASKS', N'LOCAL_ACTION_PLAN_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
    ADD [LOCAL_ACTION_PLAN_JSON] nvarchar(max) NULL;
END
GO

IF COL_LENGTH(N'amc.AGENT_TASKS', N'LOCAL_ACTION_RESULT_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
    ADD [LOCAL_ACTION_RESULT_JSON] nvarchar(max) NULL;
END
GO

IF COL_LENGTH(N'amc.AGENT_TASKS', N'TOUCHED_PATHS_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
    ADD [TOUCHED_PATHS_JSON] nvarchar(max) NULL;
END
GO

IF COL_LENGTH(N'amc.AGENT_TASKS', N'REQUIRES_ELEVATED_APPROVAL') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
    ADD [REQUIRES_ELEVATED_APPROVAL] bit NOT NULL
        CONSTRAINT [DF_AMC_AGENT_TASKS_REQUIRES_ELEVATED_APPROVAL] DEFAULT ((0));
END
GO
