SET NOCOUNT ON;
GO

IF SCHEMA_ID(N'amc') IS NULL
BEGIN
    THROW 50000, 'Schema [amc] does not exist in this database.', 1;
END
GO

IF OBJECT_ID(N'amc.LLM_PROVIDERS', N'U') IS NULL
BEGIN
    THROW 50001, 'Table [amc].[LLM_PROVIDERS] does not exist in this database.', 1;
END
GO

IF COL_LENGTH(N'amc.LLM_PROVIDERS', N'COST_PER1K_INPUT_TOKENS') IS NULL
BEGIN
    ALTER TABLE [amc].[LLM_PROVIDERS]
    ADD [COST_PER1K_INPUT_TOKENS] decimal(18,10) NOT NULL
        CONSTRAINT [DF_AMC_LLM_PROVIDERS_COST_PER1K_INPUT_TOKENS] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.LLM_PROVIDERS', N'COST_PER1K_OUTPUT_TOKENS') IS NULL
BEGIN
    ALTER TABLE [amc].[LLM_PROVIDERS]
    ADD [COST_PER1K_OUTPUT_TOKENS] decimal(18,10) NOT NULL
        CONSTRAINT [DF_AMC_LLM_PROVIDERS_COST_PER1K_OUTPUT_TOKENS] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.LLM_PROVIDERS', N'IS_API_KEY_ENCRYPTED') IS NULL
BEGIN
    ALTER TABLE [amc].[LLM_PROVIDERS]
    ADD [IS_API_KEY_ENCRYPTED] bit NOT NULL
        CONSTRAINT [DF_AMC_LLM_PROVIDERS_IS_API_KEY_ENCRYPTED] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.LLM_PROVIDERS', N'IS_AUTH_TOKEN_ENCRYPTED') IS NULL
BEGIN
    ALTER TABLE [amc].[LLM_PROVIDERS]
    ADD [IS_AUTH_TOKEN_ENCRYPTED] bit NOT NULL
        CONSTRAINT [DF_AMC_LLM_PROVIDERS_IS_AUTH_TOKEN_ENCRYPTED] DEFAULT ((0));
END
GO

IF COL_LENGTH(N'amc.LLM_PROVIDERS', N'ENCRYPTION_UPDATED_AT') IS NULL
BEGIN
    ALTER TABLE [amc].[LLM_PROVIDERS]
    ADD [ENCRYPTION_UPDATED_AT] datetime2 NULL;
END
GO
