SET NOCOUNT ON;
GO

IF SCHEMA_ID(N'amc') IS NULL
BEGIN
    THROW 50000, 'Schema [amc] does not exist in this database.', 1;
END
GO

IF OBJECT_ID(N'[amc].[LOCAL_CAPABILITIES]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[LOCAL_CAPABILITIES] (
        [ID] NVARCHAR(64) NOT NULL,
        [NAME] NVARCHAR(255) NOT NULL,
        [DISPLAY_NAME] NVARCHAR(255) NOT NULL,
        [DESCRIPTION] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_DESCRIPTION] DEFAULT (N''),
        [CATEGORY] INT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_CATEGORY] DEFAULT (0),
        [EXECUTION_TYPE] INT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_EXECUTION_TYPE] DEFAULT (0),
        [HANDLER_KEY] NVARCHAR(255) NULL,
        [SCRIPT_PATH] NVARCHAR(1024) NULL,
        [SCRIPT_CONTENT] NVARCHAR(MAX) NULL,
        [INPUT_SCHEMA_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_INPUT_SCHEMA_JSON] DEFAULT (N'{}'),
        [OUTPUT_SCHEMA_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_OUTPUT_SCHEMA_JSON] DEFAULT (N'{}'),
        [ALLOWED_ROOTS_JSON] NVARCHAR(MAX) NULL,
        [REQUIRES_APPROVAL] BIT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_REQUIRES_APPROVAL] DEFAULT ((0)),
        [IS_GENERATED] BIT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_IS_GENERATED] DEFAULT ((0)),
        [IS_ACTIVE] BIT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_IS_ACTIVE] DEFAULT ((1)),
        [VERSION] INT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_VERSION] DEFAULT ((1)),
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        [LAST_USED_AT] DATETIME2 NULL,
        [SUCCESS_COUNT] INT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_SUCCESS_COUNT] DEFAULT ((0)),
        [FAILURE_COUNT] INT NOT NULL CONSTRAINT [DF_AMC_LOCAL_CAPABILITIES_FAILURE_COUNT] DEFAULT ((0)),
        CONSTRAINT [PK_LOCAL_CAPABILITIES] PRIMARY KEY ([ID])
    );
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'LOCAL_CAPABILITY_ID') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [LOCAL_CAPABILITY_ID] NVARCHAR(64) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'LOCAL_CAPABILITY_DRAFT_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [LOCAL_CAPABILITY_DRAFT_JSON] NVARCHAR(MAX) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'LOCAL_CAPABILITY_EXECUTION_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [LOCAL_CAPABILITY_EXECUTION_JSON] NVARCHAR(MAX) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'LOCAL_ACTION_PLAN_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [LOCAL_ACTION_PLAN_JSON] NVARCHAR(MAX) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'LOCAL_ACTION_RESULT_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [LOCAL_ACTION_RESULT_JSON] NVARCHAR(MAX) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'TOUCHED_PATHS_JSON') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [TOUCHED_PATHS_JSON] NVARCHAR(MAX) NULL;
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'REQUIRES_ELEVATED_APPROVAL') IS NULL
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD [REQUIRES_ELEVATED_APPROVAL] BIT NOT NULL
            CONSTRAINT [DF_AMC_AGENT_TASKS_REQUIRES_ELEVATED_APPROVAL] DEFAULT ((0));
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AGENT_TASKS_LOCAL_CAPABILITIES')
BEGIN
    ALTER TABLE [amc].[AGENT_TASKS]
        ADD CONSTRAINT [FK_AGENT_TASKS_LOCAL_CAPABILITIES]
        FOREIGN KEY ([LOCAL_CAPABILITY_ID])
        REFERENCES [amc].[LOCAL_CAPABILITIES]([ID])
        ON DELETE SET NULL;
END
GO

/*
LocalCapabilityCategory enum mapping:
0 = Read
1 = Write
2 = Query
3 = Destructive

LocalCapabilityExecutionType enum mapping:
0 = BuiltIn
1 = PowerShell
*/
