USE [BZMGTLDB];
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'amc')
BEGIN
    EXEC('CREATE SCHEMA [amc]');
END
GO

IF OBJECT_ID(N'[amc].[SKILL_DEFINITIONS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[SKILL_DEFINITIONS] (
        [ID] NVARCHAR(64) NOT NULL,
        [NAME] NVARCHAR(255) NOT NULL,
        [CATEGORY] INT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_CATEGORY] DEFAULT (0),
        [DESCRIPTION] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_DESCRIPTION] DEFAULT (N''),
        [PROMPT_SNIPPET] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_PROMPT_SNIPPET] DEFAULT (N''),
        [ALLOWED_MCP_TOOL_NAMES_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_ALLOWED_TOOLS] DEFAULT (N'[]'),
        [PREFERRED_PROVIDER_ID] NVARCHAR(64) NULL,
        [PREFERRED_MODEL_NAME] NVARCHAR(255) NULL,
        [MAX_TOOL_CALLS] INT NULL,
        [REQUIRES_APPROVAL] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_REQUIRES_APPROVAL] DEFAULT (0),
        [IS_BUILT_IN] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_IS_BUILT_IN] DEFAULT (1),
        [IS_ENABLED] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_IS_ENABLED] DEFAULT (1),
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_SKILL_DEFINITIONS] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_SKILL_DEFINITIONS_LLM_PROVIDERS] FOREIGN KEY ([PREFERRED_PROVIDER_ID])
            REFERENCES [amc].[LLM_PROVIDERS]([ID])
    );
END
GO

IF OBJECT_ID(N'[amc].[AGENT_SKILL_ASSIGNMENTS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[AGENT_SKILL_ASSIGNMENTS] (
        [AGENT_ID] NVARCHAR(64) NOT NULL,
        [SKILL_DEFINITION_ID] NVARCHAR(64) NOT NULL,
        [IS_ENABLED] BIT NOT NULL CONSTRAINT [DF_AGENT_SKILL_ASSIGNMENTS_IS_ENABLED] DEFAULT (1),
        [ADDED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_AGENT_SKILL_ASSIGNMENTS_ADDED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_AGENT_SKILL_ASSIGNMENTS] PRIMARY KEY ([AGENT_ID], [SKILL_DEFINITION_ID]),
        CONSTRAINT [FK_AGENT_SKILL_ASSIGNMENTS_AGENTS] FOREIGN KEY ([AGENT_ID])
            REFERENCES [amc].[AGENTS]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_AGENT_SKILL_ASSIGNMENTS_SKILL_DEFINITIONS] FOREIGN KEY ([SKILL_DEFINITION_ID])
            REFERENCES [amc].[SKILL_DEFINITIONS]([ID]) ON DELETE CASCADE
    );
END
GO

IF COL_LENGTH('amc.SKILL_DEFINITIONS', 'CATEGORY') IS NULL
BEGIN
    ALTER TABLE [amc].[SKILL_DEFINITIONS]
        ADD [CATEGORY] INT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_CATEGORY] DEFAULT (0);
END
GO

UPDATE [amc].[SKILL_DEFINITIONS]
SET [CATEGORY] = 1
WHERE [ID] = N'skill-001'
   OR [NAME] = N'DB Schema Lookup';
GO

UPDATE [amc].[SKILL_DEFINITIONS]
SET [CATEGORY] = 2
WHERE [ID] = N'skill-002'
   OR [NAME] = N'Invoice Validation';
GO

UPDATE [amc].[SKILL_DEFINITIONS]
SET [CATEGORY] = 3
WHERE [ID] = N'skill-003'
   OR [NAME] = N'ERP Sync Audit';
GO

UPDATE [amc].[SKILL_DEFINITIONS]
SET [CATEGORY] = 4
WHERE [ID] = N'skill-004'
   OR [NAME] = N'Cost Analysis';
GO

/*
SkillCategory enum mapping:
0 = General
1 = Database
2 = Finance
3 = Integration
4 = Reporting
5 = Compliance
*/
