USE [BZMGTLDB];
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'amc')
BEGIN
    EXEC('CREATE SCHEMA [amc]');
END
GO

IF OBJECT_ID(N'[amc].[SKILL_DEFINITIONS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[SKILL_DEFINITIONS] (
        [ID] NVARCHAR(64) NOT NULL,
        [NAME] NVARCHAR(255) NOT NULL,
        [DESCRIPTION] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_DESCRIPTION] DEFAULT (N''),
        [PROMPT_SNIPPET] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_PROMPT_SNIPPET] DEFAULT (N''),
        [ALLOWED_MCP_TOOL_NAMES_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_ALLOWED_TOOLS] DEFAULT (N'[]'),
        [PREFERRED_PROVIDER_ID] NVARCHAR(64) NULL,
        [PREFERRED_MODEL_NAME] NVARCHAR(255) NULL,
        [MAX_TOOL_CALLS] INT NULL,
        [REQUIRES_APPROVAL] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_REQUIRES_APPROVAL] DEFAULT (0),
        [IS_BUILT_IN] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_IS_BUILT_IN] DEFAULT (1),
        [IS_ENABLED] BIT NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_IS_ENABLED] DEFAULT (1),
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_SKILL_DEFINITIONS_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_SKILL_DEFINITIONS] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_SKILL_DEFINITIONS_LLM_PROVIDERS] FOREIGN KEY ([PREFERRED_PROVIDER_ID])
            REFERENCES [amc].[LLM_PROVIDERS]([ID])
    );
END
GO

IF OBJECT_ID(N'[amc].[AGENT_SKILL_ASSIGNMENTS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[AGENT_SKILL_ASSIGNMENTS] (
        [AGENT_ID] NVARCHAR(64) NOT NULL,
        [SKILL_DEFINITION_ID] NVARCHAR(64) NOT NULL,
        [IS_ENABLED] BIT NOT NULL CONSTRAINT [DF_AGENT_SKILL_ASSIGNMENTS_IS_ENABLED] DEFAULT (1),
        [ADDED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_AGENT_SKILL_ASSIGNMENTS_ADDED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_AGENT_SKILL_ASSIGNMENTS] PRIMARY KEY ([AGENT_ID], [SKILL_DEFINITION_ID]),
        CONSTRAINT [FK_AGENT_SKILL_ASSIGNMENTS_AGENTS] FOREIGN KEY ([AGENT_ID])
            REFERENCES [amc].[AGENTS]([ID]) ON DELETE CASCADE,
        CONSTRAINT [FK_AGENT_SKILL_ASSIGNMENTS_SKILL_DEFINITIONS] FOREIGN KEY ([SKILL_DEFINITION_ID])
            REFERENCES [amc].[SKILL_DEFINITIONS]([ID]) ON DELETE CASCADE
    );
END
GO

IF OBJECT_ID(N'[amc].[EVALUATION_SCENARIOS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[EVALUATION_SCENARIOS] (
        [ID] NVARCHAR(64) NOT NULL,
        [NAME] NVARCHAR(255) NOT NULL,
        [DESCRIPTION] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_SCENARIOS_DESCRIPTION] DEFAULT (N''),
        [BASE_AGENT_ID] NVARCHAR(64) NULL,
        [TASK_NAME] NVARCHAR(255) NOT NULL,
        [INPUT] NVARCHAR(MAX) NOT NULL,
        [PROMPT_OVERRIDE] NVARCHAR(MAX) NULL,
        [SELECTED_PROVIDER_IDS_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_SCENARIOS_PROVIDER_IDS] DEFAULT (N'[]'),
        [SELECTED_SKILL_IDS_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_SCENARIOS_SKILL_IDS] DEFAULT (N'[]'),
        [IS_PINNED] BIT NOT NULL CONSTRAINT [DF_EVALUATION_SCENARIOS_IS_PINNED] DEFAULT (0),
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EVALUATION_SCENARIOS_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        [LAST_RUN_AT] DATETIME2 NULL,
        CONSTRAINT [PK_EVALUATION_SCENARIOS] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_EVALUATION_SCENARIOS_AGENTS] FOREIGN KEY ([BASE_AGENT_ID])
            REFERENCES [amc].[AGENTS]([ID]) ON DELETE SET NULL
    );
END
GO

IF OBJECT_ID(N'[amc].[EVALUATION_RUNS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[EVALUATION_RUNS] (
        [ID] NVARCHAR(64) NOT NULL,
        [EVALUATION_SCENARIO_ID] NVARCHAR(64) NOT NULL,
        [PROVIDER_ID] NVARCHAR(64) NOT NULL,
        [PROVIDER_NAME] NVARCHAR(255) NOT NULL,
        [MODEL_NAME] NVARCHAR(255) NOT NULL,
        [SKILL_NAMES_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_SKILL_NAMES] DEFAULT (N'[]'),
        [OUTPUT] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_OUTPUT] DEFAULT (N''),
        [EXECUTION_TRACE] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_TRACE] DEFAULT (N''),
        [PROMPT_TOKENS] INT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_PROMPT_TOKENS] DEFAULT (0),
        [COMPLETION_TOKENS] INT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_COMPLETION_TOKENS] DEFAULT (0),
        [TOTAL_TOKENS] INT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_TOTAL_TOKENS] DEFAULT (0),
        [COST_USD] DECIMAL(18,6) NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_COST_USD] DEFAULT (0),
        [TOOL_CALLS_USED] INT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_TOOL_CALLS_USED] DEFAULT (0),
        [DURATION_MS] BIGINT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_DURATION_MS] DEFAULT (0),
        [STATUS] INT NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_STATUS] DEFAULT (0),
        [ERROR_MESSAGE] NVARCHAR(MAX) NULL,
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EVALUATION_RUNS_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_EVALUATION_RUNS] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_EVALUATION_RUNS_EVALUATION_SCENARIOS] FOREIGN KEY ([EVALUATION_SCENARIO_ID])
            REFERENCES [amc].[EVALUATION_SCENARIOS]([ID]) ON DELETE CASCADE
    );
END
GO

IF COL_LENGTH('amc.AGENT_TASKS', 'PROVIDER_SNAPSHOT_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [PROVIDER_SNAPSHOT_ID] NVARCHAR(64) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'PROVIDER_SNAPSHOT_NAME') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [PROVIDER_SNAPSHOT_NAME] NVARCHAR(255) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'PROVIDER_SNAPSHOT_MODEL') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [PROVIDER_SNAPSHOT_MODEL] NVARCHAR(255) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'SKILL_SNAPSHOT_JSON') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [SKILL_SNAPSHOT_JSON] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'MCP_SERVER_SNAPSHOT_JSON') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [MCP_SERVER_SNAPSHOT_JSON] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'APPROVAL_EVIDENCE') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [APPROVAL_EVIDENCE] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'APPROVAL_COMMENT') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [APPROVAL_COMMENT] NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'REPLAY_OF_TASK_ID') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [REPLAY_OF_TASK_ID] NVARCHAR(64) NULL;
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'DURATION_MS') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [DURATION_MS] BIGINT NOT NULL CONSTRAINT [DF_AGENT_TASKS_DURATION_MS] DEFAULT (0);
GO
IF COL_LENGTH('amc.AGENT_TASKS', 'TOOL_CALLS_USED') IS NULL
    ALTER TABLE [amc].[AGENT_TASKS] ADD [TOOL_CALLS_USED] INT NOT NULL CONSTRAINT [DF_AGENT_TASKS_TOOL_CALLS_USED] DEFAULT (0);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AGENT_SKILL_ASSIGNMENTS_SKILL_DEFINITION_ID' AND object_id = OBJECT_ID(N'[amc].[AGENT_SKILL_ASSIGNMENTS]'))
    CREATE INDEX [IX_AGENT_SKILL_ASSIGNMENTS_SKILL_DEFINITION_ID] ON [amc].[AGENT_SKILL_ASSIGNMENTS] ([SKILL_DEFINITION_ID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EVALUATION_SCENARIOS_BASE_AGENT_ID' AND object_id = OBJECT_ID(N'[amc].[EVALUATION_SCENARIOS]'))
    CREATE INDEX [IX_EVALUATION_SCENARIOS_BASE_AGENT_ID] ON [amc].[EVALUATION_SCENARIOS] ([BASE_AGENT_ID]);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EVALUATION_RUNS_EVALUATION_SCENARIO_ID' AND object_id = OBJECT_ID(N'[amc].[EVALUATION_RUNS]'))
    CREATE INDEX [IX_EVALUATION_RUNS_EVALUATION_SCENARIO_ID] ON [amc].[EVALUATION_RUNS] ([EVALUATION_SCENARIO_ID]);
GO

IF NOT EXISTS (SELECT 1 FROM [amc].[SKILL_DEFINITIONS] WHERE [ID] = 'skill-001')
BEGIN
    INSERT INTO [amc].[SKILL_DEFINITIONS]
    (
        [ID], [NAME], [DESCRIPTION], [PROMPT_SNIPPET], [ALLOWED_MCP_TOOL_NAMES_JSON],
        [PREFERRED_PROVIDER_ID], [PREFERRED_MODEL_NAME], [MAX_TOOL_CALLS], [REQUIRES_APPROVAL],
        [IS_BUILT_IN], [IS_ENABLED], [CREATED_AT]
    )
    VALUES
    (
        'skill-001', 'DB Schema Lookup',
        'Retrieve table definitions, indexes, and stored procedure shapes through approved MCP database tools.',
        'Use this skill for database metadata requests. Prefer exact object names and return concise structured schema summaries.',
        '["xpedeon-database-tool","xpedeon-database-legacy-tool"]',
        NULL, 'Hermes 3 / tool-calling model', 4, 0, 1, 1, '2026-01-01T00:00:00'
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM [amc].[SKILL_DEFINITIONS] WHERE [ID] = 'skill-002')
BEGIN
    INSERT INTO [amc].[SKILL_DEFINITIONS]
    (
        [ID], [NAME], [DESCRIPTION], [PROMPT_SNIPPET], [ALLOWED_MCP_TOOL_NAMES_JSON],
        [PREFERRED_PROVIDER_ID], [PREFERRED_MODEL_NAME], [MAX_TOOL_CALLS], [REQUIRES_APPROVAL],
        [IS_BUILT_IN], [IS_ENABLED], [CREATED_AT]
    )
    VALUES
    (
        'skill-002', 'Invoice Validation',
        'Validate invoice records, detect anomalies, and summarize issues before posting or approval.',
        'Use this skill when validating invoices. Highlight missing fields, duplicates, suspicious amounts, and approval blockers before giving a recommendation.',
        '[]',
        NULL, 'Hermes 3 / high-precision validator', 2, 1, 1, 1, '2026-01-01T00:00:00'
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM [amc].[SKILL_DEFINITIONS] WHERE [ID] = 'skill-003')
BEGIN
    INSERT INTO [amc].[SKILL_DEFINITIONS]
    (
        [ID], [NAME], [DESCRIPTION], [PROMPT_SNIPPET], [ALLOWED_MCP_TOOL_NAMES_JSON],
        [PREFERRED_PROVIDER_ID], [PREFERRED_MODEL_NAME], [MAX_TOOL_CALLS], [REQUIRES_APPROVAL],
        [IS_BUILT_IN], [IS_ENABLED], [CREATED_AT]
    )
    VALUES
    (
        'skill-003', 'ERP Sync Audit',
        'Audit ERP sync tasks, compare system states, and call out mismatches with follow-up actions.',
        'Use this skill for reconciliation and sync audits. Focus on mismatches, source-of-truth decisions, and next-step actions.',
        '[]',
        NULL, NULL, 3, 0, 1, 1, '2026-01-01T00:00:00'
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM [amc].[SKILL_DEFINITIONS] WHERE [ID] = 'skill-004')
BEGIN
    INSERT INTO [amc].[SKILL_DEFINITIONS]
    (
        [ID], [NAME], [DESCRIPTION], [PROMPT_SNIPPET], [ALLOWED_MCP_TOOL_NAMES_JSON],
        [PREFERRED_PROVIDER_ID], [PREFERRED_MODEL_NAME], [MAX_TOOL_CALLS], [REQUIRES_APPROVAL],
        [IS_BUILT_IN], [IS_ENABLED], [CREATED_AT]
    )
    VALUES
    (
        'skill-004', 'Cost Analysis',
        'Analyze budget variance, burn rates, and overspend patterns with actionable recommendations.',
        'Use this skill for project cost analysis. Summarize overspend drivers, likely risk areas, and recommended interventions in a business-friendly format.',
        '[]',
        NULL, NULL, 2, 0, 1, 1, '2026-01-01T00:00:00'
    );
END
GO
