USE [BZMGTLDB];
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'amc')
BEGIN
    EXEC('CREATE SCHEMA [amc]');
END
GO

IF OBJECT_ID(N'[amc].[EXTERNAL_SKILL_PACKAGES]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[EXTERNAL_SKILL_PACKAGES] (
        [ID] NVARCHAR(64) NOT NULL,
        [PACKAGE_KEY] NVARCHAR(255) NOT NULL,
        [NAME] NVARCHAR(255) NOT NULL,
        [VERSION] NVARCHAR(100) NOT NULL,
        [DESCRIPTION] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_DESCRIPTION] DEFAULT (N''),
        [SOURCE_URL] NVARCHAR(2048) NOT NULL,
        [SOURCE_REPO] NVARCHAR(255) NOT NULL,
        [SOURCE_REF] NVARCHAR(255) NOT NULL,
        [MANIFEST_PATH] NVARCHAR(1024) NOT NULL,
        [RAW_SOURCE_URL] NVARCHAR(2048) NOT NULL,
        [KIND] INT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_KIND] DEFAULT (0),
        [CONTENT_HASH] NVARCHAR(128) NOT NULL,
        [MANIFEST_JSON] NVARCHAR(MAX) NOT NULL,
        [RUNTIME_TRANSPORT_TYPE] INT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_RUNTIME_TRANSPORT_TYPE] DEFAULT (3),
        [RUNTIME_ENDPOINT] NVARCHAR(MAX) NOT NULL,
        [REQUIRED_SECRET_NAMES_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_REQUIRED_SECRETS] DEFAULT (N'[]'),
        [PERMISSION_HINTS_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_PERMISSION_HINTS] DEFAULT (N'[]'),
        [DECLARED_TOOL_NAMES_JSON] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_DECLARED_TOOLS] DEFAULT (N'[]'),
        [APPROVAL_STATUS] INT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_APPROVAL_STATUS] DEFAULT (0),
        [INSTALL_STATUS] INT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_INSTALL_STATUS] DEFAULT (0),
        [IS_ENABLED] BIT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_IS_ENABLED] DEFAULT (0),
        [IMPORT_ERROR] NVARCHAR(MAX) NULL,
        [LAST_SYNC_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_LAST_SYNC_AT] DEFAULT (SYSUTCDATETIME()),
        [LAST_HEALTH_CHECK_AT] DATETIME2 NULL,
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        [UPDATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_UPDATED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_EXTERNAL_SKILL_PACKAGES] PRIMARY KEY ([ID])
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EXTERNAL_SKILL_PACKAGES_PACKAGE_KEY' AND object_id = OBJECT_ID(N'[amc].[EXTERNAL_SKILL_PACKAGES]'))
BEGIN
    CREATE INDEX [IX_EXTERNAL_SKILL_PACKAGES_PACKAGE_KEY]
        ON [amc].[EXTERNAL_SKILL_PACKAGES] ([PACKAGE_KEY]);
END
GO

IF COL_LENGTH('amc.EXTERNAL_SKILL_PACKAGES', 'KIND') IS NULL
BEGIN
    ALTER TABLE [amc].[EXTERNAL_SKILL_PACKAGES]
        ADD [KIND] INT NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGES_KIND] DEFAULT (0);
END
GO

IF OBJECT_ID(N'[amc].[EXTERNAL_SKILL_PACKAGE_INSTALLS]', N'U') IS NULL
BEGIN
    CREATE TABLE [amc].[EXTERNAL_SKILL_PACKAGE_INSTALLS] (
        [ID] NVARCHAR(64) NOT NULL,
        [EXTERNAL_SKILL_PACKAGE_ID] NVARCHAR(64) NOT NULL,
        [VERSION] NVARCHAR(100) NOT NULL,
        [APPROVAL_STATUS] INT NOT NULL,
        [INSTALL_STATUS] INT NOT NULL,
        [PROVISIONED_MCP_SERVER_ID] NVARCHAR(64) NULL,
        [NOTES] NVARCHAR(MAX) NULL,
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [DF_EXTERNAL_SKILL_PACKAGE_INSTALLS_CREATED_AT] DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT [PK_EXTERNAL_SKILL_PACKAGE_INSTALLS] PRIMARY KEY ([ID]),
        CONSTRAINT [FK_EXTERNAL_SKILL_PACKAGE_INSTALLS_PACKAGES] FOREIGN KEY ([EXTERNAL_SKILL_PACKAGE_ID])
            REFERENCES [amc].[EXTERNAL_SKILL_PACKAGES]([ID]) ON DELETE CASCADE
    );
END
GO

IF COL_LENGTH('amc.MCP_SERVERS', 'IS_MANAGED') IS NULL
BEGIN
    ALTER TABLE [amc].[MCP_SERVERS]
        ADD [IS_MANAGED] BIT NOT NULL CONSTRAINT [DF_MCP_SERVERS_IS_MANAGED] DEFAULT (0);
END
GO

IF COL_LENGTH('amc.MCP_SERVERS', 'EXTERNAL_SKILL_PACKAGE_ID') IS NULL
BEGIN
    ALTER TABLE [amc].[MCP_SERVERS]
        ADD [EXTERNAL_SKILL_PACKAGE_ID] NVARCHAR(64) NULL;
END
GO

IF COL_LENGTH('amc.SKILL_DEFINITIONS', 'EXTERNAL_SKILL_PACKAGE_ID') IS NULL
BEGIN
    ALTER TABLE [amc].[SKILL_DEFINITIONS]
        ADD [EXTERNAL_SKILL_PACKAGE_ID] NVARCHAR(64) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MCP_SERVERS_EXTERNAL_SKILL_PACKAGES')
BEGIN
    ALTER TABLE [amc].[MCP_SERVERS]
        ADD CONSTRAINT [FK_MCP_SERVERS_EXTERNAL_SKILL_PACKAGES]
        FOREIGN KEY ([EXTERNAL_SKILL_PACKAGE_ID])
        REFERENCES [amc].[EXTERNAL_SKILL_PACKAGES]([ID]);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SKILL_DEFINITIONS_EXTERNAL_SKILL_PACKAGES')
BEGIN
    ALTER TABLE [amc].[SKILL_DEFINITIONS]
        ADD CONSTRAINT [FK_SKILL_DEFINITIONS_EXTERNAL_SKILL_PACKAGES]
        FOREIGN KEY ([EXTERNAL_SKILL_PACKAGE_ID])
        REFERENCES [amc].[EXTERNAL_SKILL_PACKAGES]([ID]);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_EXTERNAL_SKILL_PACKAGE_INSTALLS_MCP_SERVERS')
BEGIN
    ALTER TABLE [amc].[EXTERNAL_SKILL_PACKAGE_INSTALLS]
        ADD CONSTRAINT [FK_EXTERNAL_SKILL_PACKAGE_INSTALLS_MCP_SERVERS]
        FOREIGN KEY ([PROVISIONED_MCP_SERVER_ID])
        REFERENCES [amc].[MCP_SERVERS]([ID]);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_MCP_SERVERS_EXTERNAL_SKILL_PACKAGE_ID' AND object_id = OBJECT_ID(N'[amc].[MCP_SERVERS]'))
BEGIN
    CREATE INDEX [IX_MCP_SERVERS_EXTERNAL_SKILL_PACKAGE_ID]
        ON [amc].[MCP_SERVERS] ([EXTERNAL_SKILL_PACKAGE_ID]);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SKILL_DEFINITIONS_EXTERNAL_SKILL_PACKAGE_ID' AND object_id = OBJECT_ID(N'[amc].[SKILL_DEFINITIONS]'))
BEGIN
    CREATE INDEX [IX_SKILL_DEFINITIONS_EXTERNAL_SKILL_PACKAGE_ID]
        ON [amc].[SKILL_DEFINITIONS] ([EXTERNAL_SKILL_PACKAGE_ID]);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EXTERNAL_SKILL_PACKAGE_INSTALLS_EXTERNAL_SKILL_PACKAGE_ID' AND object_id = OBJECT_ID(N'[amc].[EXTERNAL_SKILL_PACKAGE_INSTALLS]'))
BEGIN
    CREATE INDEX [IX_EXTERNAL_SKILL_PACKAGE_INSTALLS_EXTERNAL_SKILL_PACKAGE_ID]
        ON [amc].[EXTERNAL_SKILL_PACKAGE_INSTALLS] ([EXTERNAL_SKILL_PACKAGE_ID], [CREATED_AT]);
END
GO

/*
ExternalSkillPackageApprovalStatus enum mapping:
0 = PendingReview
1 = Approved
2 = Rejected

ExternalSkillPackageKind enum mapping:
0 = ManagedMcp
1 = AgentSkill

ExternalSkillPackageInstallStatus enum mapping:
0 = Draft
1 = Approved
2 = Provisioned
3 = Healthy
4 = HealthCheckFailed
5 = Uninstalled

MCPTransportType enum mapping:
0 = SSE
1 = Stdio
2 = WebSocket
3 = Http
*/
